### ISSUE TITLE
Distinguish between errors and warnings

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/power-dev#204]
I've run the power checker manually on some data from [the tip of power-dev/r1.0](https://github.com/mlcommons/power-dev/commit/ed3e0af9ffc0cf14bb1fd2f29e1f89718141cee9) to establish the "baseline" to when running @nvpohanh's [integration](https://github.com/mlcommons/inference/pull/873).

I see two types of issues reported on my data:

1. A couple of genuine power analyzer errors - I probably need to rerun those experiments:
<pre>
[ ] Check errors and warnings from PTD logs                                                                                                                                                                
        '03-09-2021 15:26:20.358: ERROR: Bad watts reading nan from WT310' in ptd_log.txt

ERROR: Not all checks passed
</pre>

2. Many warnings related to higher than desired measurement uncertainty. There's actually nothing I can do about it: the WT333E can only measure power from 1.2 W up, and I'm measuring at around 10 W.
<pre>
[ ] Check errors and warnings from PTD logs
        '03-09-2021 21:17:42.684: WARNING: Uncertainty 1.05% above 1.00% limit for the last measurement sample!' in ptd_log.txt.

ERROR: Not all checks passed
</pre>

I think the summary line should a WARNING in this case, not an ERROR.

Regardless, the run finished with two cheerful messages 
<pre>
All checks passed

All checks passed
</pre>

I have no way of telling whether these message relate to some successful experiments, or it is an (incorrect) summary of the whole check (because the check contained the above errors).

**Comment by nvpohanh** [comment]
I have also see `Bad watts reading nan` error....

**Comment by psyhtest** [comment]
After running the integrated script, I see all my good submissions being marked as invalid with a non-user friendly message:

```
[x] Check client sources checksum

[x] Check server sources checksum

[x] Check PTD commands and replies

[x] Check UUID

[x] Check session name

[x] Check time difference

[x] Check client server messages

[ ] Check results checksum

        list.remove(x): x not in list


[x] Check errors and warnings from PTD logs

[x] Check PTD configuration

[x] Check debug is disabled on server-side


ERROR: Not all checks passed
```

**Comment by psyhtest** [comment]
Good to see that `WARNING`s are no longer `ERROR`s, but they do not get propagated to the submission checker's summary as such.

**Comment by dmiskovic-NV** [comment]
> 1. Many warnings related to higher than desired measurement uncertainty. There's actually nothing I can do about it: the WT333E can only measure power from 1.2 W up, and I'm measuring at around 10 W.
> 
> [ ] Check errors and warnings from PTD logs
>         '03-09-2021 21:17:42.684: WARNING: Uncertainty 1.05% above 1.00% limit for the last measurement sample!' in ptd_log.txt.
> 
Hello,
I am a bit curious where 1.2W number came from, care to elaborate?

Since lowest range of WT333E power meter is 75W (for US wall power) or 150W (for EU wall power) it seems you are using wrong meter for power level. Probably best course of action would be to use WT310E which can go to 5mA range (750mW//1.5W US/EU range)
Uncertainty coming from meter when measuring 10W is 170mW which is 1.7%.

uncertainty calculations:
https://tmi.yokogawa.com/us/library/resources/faqs/power-analyzer-accuracy-and-basic-uncertainty-calculator/

**Comment by psyhtest** [comment]
Hi @dmiskovic-NV, sure. Quoting from my email to the Power WG from 4 February 2021:

> A follow-up question about the measurement ranges given in the
Yokogawa WT300 series spec [1].

> On page 4, the current ranges are depicted as:
WT310E: 50 uA .. 26 A.
WT310EH: 10 mA .. 40 A.
WT332E/WT333E: 5 mA .. 26 A

> On page 11, the current ranges are listed as:
WT310E: 5 mA/10 mA/20 mA/50 mA/100 mA/200 mA/0.5 A/1 A/2 A/5 A/ 10 A/20 A
WT310EH: 1 A/2 A/5 A/10 A/20 A/40 A
WT332E/WT333E: 0.5 A/1 A/2 A/5 A/10 A/20 A

> The way I read this is as follows.

> For WT310E, the narrowest current range is I = (50, 5000) uA = (0.050,
5.000) mA. Therefore, at the UK voltage of 240 V, the narrowest power
range that can be measured is thus P = (12, 1200) mW = (0.012, 1.200)
W. Extending the range to I = (0.050, 50.000) mA would allow me to
measure P = (12, 12000) mW = (0.012, 12.000) W. To measure Raspberry
Pi 4 consuming between 3.4 W to 7.6 W under load [2], I should use the
latter range then.

> For WT310EH, the narrowest current range is I = (10, 1000) mA. At 240
V, the narrowest power range is thus P = (2.4, 240) W. While the RPi4
power consumption is in this range, measurements will probably be too
imprecise to be useful. However, this should hopefully be alright for
devices in the 20-70 W range?

This got confirmed then.

Yokogawa WT333 is all I could get for this submission round in time. I'm getting WT310 for the next one.
