### ISSUE TITLE
Yokogawa WT500 Channel Issues

### ISSUE THREAD

**Issue by trevor-cockrell** [mlcommons/power-dev#220]
Currently the `server.py` requires the `-c` flag if the system is a multichannel one. This argument **requires** the starting channel followed by the number of channels to utilize.

However, the WT500 uses this flag differently: the `-c` flag is provided with a **single number** that indicates the total number of channels to analyze, starting from `1`. 

For example, `-c 2` would measure across channels `1,2` on the WT500.

This is a problem because in the `server` code, `-c` cannot be provided with just a single number.

Additionally, after making that modification to test on my end, I came to an issue with lines 152-155 in `lib/server.py` needing to be removed for this specific scenario. Otherwise the program would throw a runtime error (since I've only supplied a single digit).

**Comment by dmiskovic-NV** [comment]
This is interesting enough check I asked for because we were focusing on wt333 (I didn't check for wt500 since it wasn't among expected meters) which indeed has different syntax.
