### ISSUE TITLE
Proposal: simplify log gathering/storing

### ISSUE THREAD

**Issue by xzfc** [mlcommons/power-dev#227]
As for round 1.0, we had the following options:

* `--fetch-logs` to gather all logs on the SUT, i.e. to transfer power logs (`spl.txt`) from the server to the client.
* `--send-logs` to gather all logs on the Director, i.e. to transfer loadgen logs (`mlperf_log_summary` and so on) from the client to the server.

---

History and reasoning behind them:

* `--send-logs` is made optional because the loadgen logs could be quite large (a few megabytes).
* Krai and @nvpohanh prefer to gather logs on the SUT.
* `--fetch-logs` is added in #138 by request from Krai.
  We made this optional and disabled by default to minimize the chance of breaking other submitters' workflow in round 1.0.
* AFAIK Nvidia uses neither of these options. Instead, they store logs on a shared NFS (network file system) and merge them manually or using their own automation.
* We prepend timestamps to the output log directory name. in E.g. `--output OUTDIR` would give us `OUTDIR/2020-12-28_15-20-52` and so on. Made by an old (2021-01-11) request from Eric from NVIDIA.
  > Having to remove the output folder before the script runs feels unnecessary.  Can the data be stored with the timestamp and/or label in the path by default?
  > I know it can be scripted, but that is how repeated loadgen data is stored w/o users having to specify it.

---

For the next round we could simplify the workflow and implement some or all of the following proposals:

* [ ] 1. Enable `--fetch-logs` by default (make it non-configurable).
* [ ] 2. Since all submitters already expected to have a bunch of logs on the SUT from non-power runs (e.g. accuracy or compliance), maybe we could get rid of `--send-logs` to make it consistent with non-power runs?
* [ ] 3. If 1 and 2 are done, we could disable log storing on the server at all.
* [ ] 4. Not sure if the timestamps request is still applicable, but it made Krai automation slightly more complex than it could be.
      We could remove this from `client.py` and let the user script it by themselves if needed (e.g. `--output "OUTDIR/$(date +%F_%H_%M_%S)"`).

**Comment by ykurlaev** [comment]
Implementation in the current PR automatically copy all logs from the server to the client and removes them from the server.
ptd.logFile and server.outDir config options are removed, instead a temporary directory is used.

For the fourth point, implemented an option for the client "-T/--no-timestamp-path| to remove automatic timestamp adding from the output path. Also added "-t/--timestamp-path" which right now does nothing (is set by default) but in future we can reverse the default behavior if we want.
