### ISSUE TITLE
Force UTC timezone in client and server

### ISSUE THREAD

**Issue by ykurlaev** [mlcommons/power-dev#232]
To eliminate all potential timezone issues.

* [x] Already implemented for `client.py`/`server.py`.
* [x] PTDaemon: could be done using `export TZ=UTC`.
* [ ] Loadgen: should be fixed in the loadgen source code.

**Comment by s-idgunji** [comment]
Hi @ykurlaev  - Is this issue now done, and can be closed.

**Comment by s-idgunji** [comment]
I believe this is fixed and issue is merged, we should be able to close.  @psyhtest  and @araghun  can you check and confirm ?

**Comment by araghun** [comment]
Set UTC timezone for PTD #234
 Merged

**Comment by nvpohanh** [comment]
@araghun @ykurlaev FYI, the loadgen now logs the power_start/end timestamps in UTC

**Comment by nvpohanh** [comment]
https://github.com/mlcommons/inference/pull/898 has been merged
