### ISSUE TITLE
Submission checker: YokogawaWT310E is not supported

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/power-dev#238]
As part of supporting the Qualcomm audit, I've re-run all benchmarks with a new Yokogawa WT310E power meter. (For the submission, we had a WT333E on loan, while waiting for the WT310E to arrive.)

Unfortunately, the submission checker complains about `YokogawaWT310E` not being supported:

<pre>
<b>[strattja@ax530b-03-giga ~]&dollar;</b> python3.8 \                                                                                                                                                                  
> $(ck locate env --tags=mlperf,inference,r1.0)/inference/tools/submission/submission-checker.py \                                                                                                         
> --more-power-check --submitter Qualcomm --version v1.0 --input /tmp/inference_results_v1.0
...
INFO    Sucessfully loaded MLPerf log from closed/Qualcomm/results/r282_z93_q5-qaic-v1.3.14-aic100/resnet50/offline/accuracy/mlperf_log_detail.txt.
INFO    Detected power logs for closed/Qualcomm/results/r282_z93_q5-qaic-v1.3.14-aic100/resnet50/offline
INFO    Sucessfully loaded MLPerf log from closed/Qualcomm/results/r282_z93_q5-qaic-v1.3.14-aic100/resnet50/offline/performance/run_1/mlperf_log_detail.txt.
INFO    Sucessfully loaded MLPerf log from closed/Qualcomm/results/r282_z93_q5-qaic-v1.3.14-aic100/resnet50/offline/performance/run_1/mlperf_log_detail.txt.
INFO    Sucessfully loaded MLPerf log from closed/Qualcomm/results/r282_z93_q5-qaic-v1.3.14-aic100/resnet50/offline/performance/run_1/mlperf_log_detail.txt.
[x] Check client sources checksum

[x] Check server sources checksum

[ ] Check PTD commands and replies

        Power meter &apos;YokogawaWT310E&apos; is not supportable. Only YokogawaWT210, YokogawaWT500, YokogawaWT500_multichannel, YokogawaWT310, YokogawaWT330E, YokogawaWT330_multichannel are supported.

[x] Check UUID
                                                                            
[x] Check session name
                                                                                                                                                                     
[x] Check time difference
                                                                                                                                                                   
[x] Check client server messages
                                                                                                 
[x] Check results checksum
                                                                                                                                                               
[x] Check errors and warnings from PTD logs
                                                                                                                                   
[x] Check PTD configuration
                                                                                                                                                              
[x] Check debug is disabled on server-side

ERROR: Not all checks passed                                                                          

<font color="#DC322F">ERROR  </font> Power WG check.py did not pass for: closed/Qualcomm/results/r282_z93_q5-qaic-v1.3.14-aic100/resnet50/offline/performance
<font color="#DC322F">ERROR  </font> closed/Qualcomm/results/r282_z93_q5-qaic-v1.3.14-aic100/resnet50/offline/performance/run_1 has issues
</pre>

Surely, it's just a matter of adding the string to some predefined list.

**Comment by psyhtest** [comment]
For all our intents and purposes, the WT310E should be the same as the WT310. PTDaemon, however, does not recognize it:

<pre>
&dollar; /ptd-linux-x86 -h
...
for AC power measurements:                                                                           
  0. *Dummy (testing only)             8. Yokogawa WT210
 14. Instek GPM-8212                  16. ZES LMG450:1-Channel
 17. ZES LMG450:4-Channel             18. ZES LMG500:1-Channel                    
 19. ZES LMG500:4-Channel             22. ZES LMG95            
 23. Voltech PM1000+                  25. Infratek 107A-1         
 28. Xitron 280X:1-Channel            31. Chroma 66202                           
 33. Hioki 3334                       35. Yokogawa WT500:1-Channel
 36. Yokogawa WT500:MULTIPHASE        37. ZES LMG450:3-Phase                    
 38. ZES LMG500:3-Phase               41. N4L PPA15X0:1-Channel
 44. N4L PPA55X0:1-Channel            47. Yokogawa WT1800:1-Channel
 48. Yokogawa WT500:MULTICHANNEL      <b>49. Yokogawa WT310</b>                                  
 50. N4L PPA5X0:1-Channel             51. Chroma 66203 66204:1ch                     
 52. Yokogawa WT330:1-Channel         53. Yokogawa WT330:3-Phase            
 56. Tektronix PA1000                 57. Hioki PW3335                          
 58. Hioki PW3336:1-Channel           59. Hioki PW3336:2-Channel
 60. Hioki PW3337:1-Channel           61. Hioki PW3337:3-Channel
 62. Hioki PW3337:3-Phase             65. Chroma 66205
 66. Yokogawa WT5000:1-Channel        67. Yokogawa WT5000:3-Phase       
 68. ZES LMG610                       69. ZES LMG641:1-Channel
 70. ZES LMG671:1-Channel             75. Instek GPM-8310
 76. Instek GPM-8213                  77. Yokogawa WT330:MULTICHANNEL
</pre>

**Comment by psyhtest** [comment]
I think we can simply invert the dictionary and add `Yokogawa310E` there as follows:
<pre>
SUPPORTED_MODEL = {
    "YokogawaWT210" : 8,
    "YokogawaWT500" : 35,
    "YokogawaWT500_multichannel" : 48,
    "YokogawaWT310" : 49,
    "YokogawaWT310E" : 49,
    "YokogawaWT330E" : 52,
    "YokogawaWT330_multichannel" : 77,
}
</pre>
and then update the rest of the script accordingly, using the keys instead of the values, and vice-versa.

**Comment by s-idgunji** [comment]
@psyhtest   -  We had added a limited set of meters that we want to ensure are validated prior submission, so if we want to add Yokogawa310E , we can move forward as you have proposed.  Have you validated that the meter outputs look reasonably as expected as 310 from your prior data collection during v1.0 submission ?

**Comment by psyhtest** [comment]
@s-idgunji So far, I have only validated the Datacenter submission.

- From the v1.0 submission with the WT333E:
<pre>
resnet50/offline 100077.000000 with power_metric = 561.943939
resnet50/server 78501.900000 with power_metric = 533.812000
ssd-resnet34/offline 1777.910000 with power_metric = 598.093263
ssd-resnet34/server 1557.430000 with power_metric = 547.826500
</pre>

- From a recent rerun with the WT310E:
<pre>
resnet50/offline 100452.000000 with power_metric = 566.887367
resnet50/server 78501.900000 with power_metric = 536.106667
ssd-resnet34/offline 1773.960000 with power_metric = 603.937761
ssd-resnet34/server 1557.430000 with power_metric = 554.615000
</pre>

The performance results are very close, but the power results are 3-7 W higher with the WT310E. I can attribute this a new [ST4000NM002A HDD](https://www.seagate.com/www-content/datasheets/pdfs/exos-7-e8-data-sheet-DS1957-2-1904US-en_US.pdf) added to the system. It's idle average power is 5.4 W.
