### ISSUE TITLE
Yokogawa WT310E Ethernet configuration

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/power-dev#254]
Can anyone please share their config file for configuring Ethernet access with Yokogawa WT310E or another meter? No matter what I try, I get a socket error 111, while the meter is perfectly pingable on the network. (I'll share a log shortly.)

**Comment by psyhtest** [comment]
```
$ /local/mnt/workspace/mlcommons/power-main/inference_v1.0/ptd-linux-x86 49 -n 10.444.167.221
  ****************************************************************************
                      ***********************************
                               SPEC PTDaemon Tool
                        Version 1.9.2-e8c7a49a-20201208
                      ***********************************
                     Licensed Materials - Property of SPEC
     Copyright 2006-2020 Standard Performance Evaluation Corporation (SPEC)
                              All Rights Reserved.
  For use with benchmark products from SPEC and authorized organizations only.
  ****************************************************************************


TCP IPV4 interface specified.
Selected power meter 'Yokogawa WT310' from wt310.cpp
Calculated PTD CRC: 0xe8c7a49a, 4100000
08-02-2021 11:25:41.068: Attempting to connect to measurement device type 49...
08-02-2021 11:25:41.069: ERROR: socket failed with error: 111
08-02-2021 11:25:41.069: ERROR: serial port open failed with error 0.
08-02-2021 11:25:41.069: ERROR: Invalid device type specified.
```

**Comment by psyhtest** [comment]
The same error with the order of the arguments as coming from the MLPerf Python workflow:
```
$ /local/mnt/workspace/mlcommons/power-main/inference_v1.0/ptd-linux-x86 -n 49 10.444.167.221
  ****************************************************************************
                      ***********************************
                               SPEC PTDaemon Tool
                        Version 1.9.2-e8c7a49a-20201208
                      ***********************************
                     Licensed Materials - Property of SPEC
     Copyright 2006-2020 Standard Performance Evaluation Corporation (SPEC)
                              All Rights Reserved.
  For use with benchmark products from SPEC and authorized organizations only.
  ****************************************************************************


TCP IPV4 interface specified.
Selected power meter 'Yokogawa WT310' from wt310.cpp
Calculated PTD CRC: 0xe8c7a49a, 4100000
08-02-2021 11:29:01.240: Attempting to connect to measurement device type 49...
08-02-2021 11:29:01.240: ERROR: socket failed with error: 111
08-02-2021 11:29:01.240: ERROR: serial port open failed with error 0.
08-02-2021 11:29:01.240: ERROR: Invalid device type specified.
```

**Comment by trevor-cockrell** [comment]
My ethernet-configured analyzer is not available to check right now, but I've been using windows+the TMCTL driver without issue. I can check with Linux when I have the analyzer available. 

If curious on how I got USB/ethernet working on windows:
I had to grab Yokogawa's drivers from [here](https://tmi.yokogawa.com/us/library/documents-downloads/software/tmctl/) and drop the DLLs from the zip file's `/dll` folder into the directory I was executing PTDaemon from. I also had to make sure that I didn't have any other YKMUSB drivers installed on the system (those were being prioritized on the path).

After that, passing the `-y` flag to PTDaemon for either USB or ethernet worked as expected.

**Comment by psyhtest** [comment]
Thanks Trevor! Before trying on Linux, I had actually failed to make the meters work from Windows. You instructions (especially the hint to uninstall YKMUSB) would have helped.

**Comment by trevor-cockrell** [comment]
Oh absolutely, it would have helped us on v1.0 had I figured it out sooner... 

Maybe I can find a spot in one of our appendices to stick this info for other potential strugglers? Any suggestions?

**Comment by psyhtest** [comment]
[BKM](https://docs.google.com/document/d/1in1bcJGhOYbKcHKaJ4h6oPLvmcJtneIb_oQJBbvxnys/edit)?

**Comment by s-idgunji** [comment]
> Thanks Trevor! Before trying on Linux, I had actually failed to make the meters work from Windows. You instructions (especially the hint to uninstall YKMUSB) would have helped.

@psyhtest  - Is this resolved  for you ?   One approach would be to highlight issues that have solutions rather than capturing each solution in the BKM doc.

**Comment by psyhtest** [comment]
This issue is not resolved for me, but I have a workaround - to use USB.

**Comment by dmiskovic-NV** [comment]
Yokogawa meters can't be used from linux using ethernet since they are relying on LXI layer on top of TCP-IPv4.
Workaround is to use either GPIB or Windows :(

**Comment by psyhtest** [comment]
Thank you @dmiskovic-NV ! I've been pulling my hair out about this (not that much of it has left anyway!)
