### ISSUE TITLE
Checker needs to be checked 

### ISSUE THREAD

**Issue by s-idgunji** [mlcommons/power-dev#255]
From the meeting on 08/04/21 , I understand that @psyhtest   reviewed and said the checker code was not checked  against itself for a hash , but this was a requirement in v1.0 , and it included the directory where checker is present.  So I want to understand and resolve this issue?   Notes from earlier for reference  @araghun  (for reference)

March 2, 2021

	Checker hashes files from the entire folders. What if there are other files/folders in the parent directory. What happens to the validity of the submissions? 
•	Tried with Checker and it seems to work. Question is about the Audit process.
•	Can Dell share an example with the Folder/Directory structure to illustrate the problem?

**Comment by psyhtest** [comment]
The checker only runs on completed power logs. Even if someone tempers with the checker to make it appear to pass, then anyone else can check the same logs with the unmodified checker and point out the fraud. Therefore, it is not an issue.

**Comment by psyhtest** [comment]
There's actually a very good reason for not requiring the checker to be hashed. A simple problem that can be addressed during post-processing of the logs like https://github.com/mlcommons/power-dev/pull/252 does not need rehashing and all the pain that goes with it...

**Comment by s-idgunji** [comment]
> There's actually a very good reason for not requiring the checker to be hashed. A simple problem that can be addressed during post-processing of the logs like #252 does not need rehashing and all the pain that goes with it...

I think you need to provide the reason which was missed in above comment.   I do not see any circular issues but if I missed it,  please point out.  I do not agree that it's not an issue as written by the previous comment either.   Issue is about effort ,  to ease post-submission process , submitters can check and be consistent.  So we have checkers.  If inadvertent mistakes are made during checking a golden check will help.  It's about automating to improve verifiability.   

To be clear, this is not a new issue, just pointing out that during v1.0 , along with all the hashing checks proposed, the one on checker was also agreed, so if it got dropped, I'd like to understand the reason.
