### ISSUE TITLE
Could you give us a tutorial about how to use this? Thank you

### ISSUE THREAD

**Issue by Water2style** [mlcommons/power-dev#256]
I have tested the MLPerf-Inference, I also want to get the power data of the inference , how can I do that? thank you!

**Comment by psyhtest** [comment]
@Water2style Is your organization a member of MLCommons?

**Comment by Water2style** [comment]
> @Water2style Is your organization a member of MLCommons?

Hi, I'm a master student in Chamers University of Technology. I don't know if it is a member of MLCommons

**Comment by psyhtest** [comment]
Chalmers (a great university, by the way!) is not a member. Unfortunately, the power workflow contains SPEC's PTDaemon component licensed only to MLCommons members (and only those who sign an additional EULA).

**Comment by s-idgunji** [comment]
Agree with @psyhtest and confirming that there is a licensing requirement.  If we can get help from academia to develop a flow to use PyVisa or something that does not require licensing,  then it can be used as an alternate to reproduce the results.
