### ISSUE TITLE
Versions being used for v1.1

### ISSUE THREAD

**Issue by s-idgunji** [mlcommons/power-dev#258]
Hi  @psyhtest  and @araghun 

I  asked Ashwin (@ashwin )  communicate this to avoid issues post submissions,   given changes happening over the last two weeks.  @nvpohanh   can you comment further.  Adding this to communicate for visibility to Power WG.  If others can comment with their versions , that would be good too.

This is the power-dev commit NVIDIA  are using:   

POWER_DEV_URL = https://github.com/mlcommons/power-dev.git
POWER_DEV_HASH = efa1489722d7a488c1bc875b0e266d98fe0da7e3

**Comment by psyhtest** [comment]
@s-idgunji I believe we don't need to specify commit hashes explicitly, as we have the sources checksums for that. For example, Any commit on the r1.1 branch before today will have one checksum. Any commit until the deadline will have another checksum.

See also my comment [here](https://github.com/mlcommons/power-dev/pull/257#issuecomment-896184432).

**Comment by nvpohanh** [comment]
The source checksums should be good enough to tell which commit hash is being used.
