### ISSUE TITLE
Option for auto/max ranging

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/power-dev#260]
For power submissions, we first perform a ranging run to determine the maximum current range, and then a test run with exactly the same parameters with the power meter set to that range.

For v1.0, we performed the ranging run under the Auto settings. It worked well across all kinds of system from Edge to Datacenter. For v1.1, we initially switched to perform ranging under the Max range (e.g. 20 A), but had to [roll that back](https://github.com/mlcommons/power-dev/pull/257) because it caused [issues for low power systems](https://github.com/mlcommons/power-dev/issues/253).

For v2.0, we would like to have an option for the ranging mode, defaulting to Auto.

**Comment by arjunsuresh** [comment]
@psyhtest Is there any advantage of using the Max mode as compared to the auto mode for ranging? Just trying to understand the reason for changing to Max mode from Auto mode.
