### ISSUE TITLE
Submission checker: YokogawaWT330 is not supported

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/power-dev#266]
For some of our upcoming v2.1 submissions, we are using an older Yokogawa WT330 model. In a very similar way to https://github.com/mlcommons/power-dev/issues/238, the compliance checker complains about this meter not being supported. For all intents and purposes, however, it should be the same as WT330E. The solution is also similar:

```
diff --git a/compliance/check.py b/compliance/check.py
index 916096c..e1cc6c9 100755
--- a/compliance/check.py
+++ b/compliance/check.py
@@ -41,6 +41,7 @@ SUPPORTED_MODEL = {
     "YokogawaWT500_multichannel": 48,
     "YokogawaWT310": 49,
     "YokogawaWT310E": 49,
+    "YokogawaWT330": 52,
     "YokogawaWT330E": 52,
     "YokogawaWT330_multichannel": 77,
 }
```

I'll create a PR to the r2.1 branch tomorrow.

**Comment by psyhtest** [comment]
Need to update the `power-dev` submodule in the `inference` repository.

**Comment by s-idgunji** [comment]
Somehow this issue was not raised in the Power WG meeting we had on 08/02.  @psyhtest  - is this in the r2.1 branch already ?
