### ISSUE TITLE
Using v2.0 power repo for v2.1 submission

### ISSUE THREAD

**Issue by anirban-ghosh** [mlcommons/power-dev#267]
Hi, 

The recent update in MLPerf power repo for v2.1 is too late for NVIDIA to integrate into our v2.1 submission pipeline.  The v2.0 commit is 3 commits behind TOT.  The changes v/s the v2.0 commit that NVIDIA is currently using are:
•	A README update
•	Relax time difference between Server and Client  ( v2.0 is more aggressive has a more aggressive time difference requirement)
•	Add a new mode for ranging phase  (but still allows for v2.0 ranging method)

Since the changes don't affect existing setups, can NVIDIA use the v2.0 power repo instead of TOT?

**Comment by psyhtest** [comment]
I'm in favour of this, but how is it going to work with the submission checker?

**Comment by psyhtest** [comment]
I believe that that the checker still considers the v2.0 set of file hashes as valid, so that should not be a problem.

**Comment by s-idgunji** [comment]
Reviewed in Power WG on 08/02 and accepted with no objections.  Closing
