### ISSUE TITLE
Issues with measuring power of low power devices

### ISSUE THREAD

**Issue by dmiskovic-NV** [mlcommons/power-dev#280]
**Important note:**
- We must not abandon ranging for submission.
- We must fix how range is selected (based on ranging run data)

Problem statement:
There are some issues and potentially erroneous (under reporting) power reporting from PTD when measuring power at range near max current of low power devices.
Root cause:
Meters by default use crest factor of 3. Crest factor is ratio of peak value of current and its RMS value. If current value is overshot, PTD will not detect it because meters state it one status register. (next version of PTD will have that check)
Area of exposure:
DUTs that have low power factor that are operating below 75W

Proposed fix:
change ranging code in manner that if max power consumed is under 75W (and power factor is in at least one sample below 0.8) that requested current range is 40% above highest value of current seen in ranging run.
40% is number i pulled out of thin air, so it is very open to discussion.

Rationale:
IEC 61000-2-3 (https://emcfastpass.com/wp-content/uploads/2017/04/Applicability_flow_chart.pdf) exempts <75W devices from adhering to any limitations with regards to number of harmonics and waveform of consumed current
example of current waveforms of units with lousy and with decent power factor
![image](https://user-images.githubusercontent.com/78380960/213113553-bf1f1087-e067-4915-b245-c2c773fea4d8.png)
ref: OnSemi PFC handbook (https://www.onsemi.com/pub/Collateral/HBD853-D.PDF)

**Comment by arjunsuresh** [comment]
Thank you @dmiskovic-NV for raising this issue. Can you please do a PR for the change seeds for inference 3.0 is going to be released soon?

**Comment by dmiskovic-NV** [comment]
more reading material
https://assets.testequity.com/te1/Documents/pdf/power-measurements_AC-DC-an.pdf
pg 16:
Power supplies can often exhibit a current crest factor of around 4 and up to 10.
since we want to emulate that with static crest factor of 3, it appears we need to set range 3.33 over highest seen
