### ISSUE TITLE
Manually setting the range is broken

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/power-dev#283]
The following command used to work for me:
```
time ck run cmdgen:benchmark.image-classification.qaic-loadgen --model=resnet50 \
--sdk=1.8.3.7 --sut=eb6 --mode=performance --scenario=offline --target_qps=699 \
--power --power_server_port=4949 --power_server_ip=192.168.4.3 \
--power_max_amps=0.234 --power_max_volts=300 --timestamp --verbose
```
but now it returns:
```
ptd-server 2023-02-07 08:07:40,119 [INFO] Sending reply to client 'Error setting current range: None'
ptd-server 2023-02-07 08:07:40,120 [INFO] Connection closed
ptd-server 2023-02-07 08:07:40,120 [WARNING] Client connection closed unexpectedly
ptd-server 2023-02-07 08:07:40,123 [INFO] Done processing
```

<details>
<pre>
ptd-server 2023-02-07 07:06:55,599 [INFO] Connected to PTDaemon
ptd-server 2023-02-07 07:06:55,599 [INFO] Sending to ptd: 'RR'
02-07-2023 07:06:55.599: Response to client sent: Ranges,1,0.200000,1,300.000000
ptd-server 2023-02-07 07:06:55,599 [INFO] Reply from ptd: 'Ranges,1,0.200000,1,300.000000'
ptd-server 2023-02-07 07:06:55,599 [INFO] Initial range for Amps is Auto for Volts is Auto
ptd-server 2023-02-07 07:06:55,599 [INFO] Sending to ptd: 'SR,V,300.0'
02-07-2023 07:06:55.600: Volt range set to 300.000000V
02-07-2023 07:06:57.101: Response to client sent: Range V changed
ptd-server 2023-02-07 07:06:57,101 [INFO] Reply from ptd: 'Range V changed'
ptd-server 2023-02-07 07:06:57,101 [INFO] Sending to ptd: 'SR,A,None'
02-07-2023 07:06:57.101: ERROR: invalid range 0.000000A requested
</pre>
</details>

I don't know if [hastily resolving conflicts](https://github.com/mlcommons/power-dev/pull/273#issuecomment-1416180017) ahead of the code freeze has something to do with it.

@arjunsuresh @araghun @s-idgunji

**Comment by arjunsuresh** [comment]
Hi @psyhtest yes, it indeed happened due to the merge. [This PR](https://github.com/mlcommons/power-dev/pull/284) should fix it.

**Comment by s-idgunji** [comment]
@psyhtest  -  Dejan worked with Arjun to undo the fix that led to this issue. Can you check if that solution works ?

**Comment by arjunsuresh** [comment]
@psyhtest I have made a [new PR](https://github.com/mlcommons/power-dev/issues/283) removing other changes not related to this issue. Please review it.
