### ISSUE TITLE
PTD 1.10.0 is not supported by the submission checker

### ISSUE THREAD

**Issue by arjunsuresh** [mlcommons/power-dev#285]
When we are running the submission checker we are getting the below error
```
[ ] Check PTD commands and replies
	PTD version '1.10.0' is not supported. Supported versions are 1.9.1 and 1.9.2
```

**Comment by s-idgunji** [comment]
@pgmpablo157321  - Let's add the update so that checker accepts v1.10.0 . This is the official release from SPEC that supersedes 1.9.x and SPEC has asked us to use this version.  The SW was made available a while ago, but the checker may need updates.
